### ISSUE TITLE
vertical: add summary of by levels at top of report [5]

### ISSUE THREAD

**Issue by srosanba** [RhoInc/sas-codebook#7]
Complete list of all combinations of the by variables and count of obs within each level. Could run into width issues if lots of variables are specified. Might need to go landscape for this first page and then flip back to portrait for subsequent pages.

**Comment by jwildfire** [comment]
priority = 5/10

**Comment by srosanba** [comment]
added to branch 'enhancements', not yet in 'master'

**Comment by srosanba** [comment]
Added to v0.12
